version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO=$(aws ecr describe-repositories --repository-names study-li --ouput text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - docker build -t $IMAGE .
      - coker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"study-li","imageUri":"%s"}]' $IMAGE > imagedefinitions.json 
artifacts:
  files: imagedefinitions.json
